### PR TITLE
Fix for Detecting Pi Zero 

### PR DESCRIPTION
**Pull request by moelski**
added alternate Processor Detection (Pi Zero works that way)
some small changes to the Blink Demo

Hi gerado, 
I´ve just created a PR for my changes. Maybe you can add it to the develop branch and merge the develop into master ... 

Dominik

### CODE REVIEW

**Comment by JTrotta** [comment]
Thanks for pulling.
I see where the problem is. But I still like to identify right hardware from firmware. I will change this today

**Comment by moelski** [comment]
> But I still like to identify right hardware from firmware. I will change this today

Great. That´s what I would prefer, too.

**Comment by JTrotta** [comment]
This is the problem:
New version to detect RPI3:
`        private static uint GetProcessorBaseAddress(Processor processor)
        {
            switch (processor)
            {
                case Processor.Bcm2708:
                    return OP.BCM2835_GPIO_BASE;
                case Processor.Bcm2709:
                case Processor.Bcm2835: 
                    return OP.BCM2836_GPIO_BASE;
                default:
                    throw new ArgumentOutOfRangeException("processor");
            }
        }`

Original version to detect:
`        private static uint GetProcessorBaseAddress(Processor processor)
        {
            switch (processor)
            {
                case Processor.Bcm2708:
                    return Interop.BCM2835_GPIO_BASE;
                case Processor.Bcm2709:
                    return Interop.BCM2836_GPIO_BASE;
                default:
                    throw new ArgumentOutOfRangeException("processor");
            }
        }`

But the real problem is here:
`        public Processor Processor
        {
            get
            {
                return Enum.TryParse(ProcessorName, true, out Processor processor) ? processor : Processor.Unknown;
            }
        }`

The processor is get by the name coming from the string `ProcessorName`, instead from the firmware version.
May you confirm me what name come from PIZero?
If I'm correct, will change Processor Detection from scratch, using, "ALWAYS", the firmware number.

**Comment by moelski** [comment]
Hi !

This comes from the Zero (with your original Code)
```
Processor      : Bcm2835
Processor Name : BCM2835
Model          : Zero
```

> Detection from scratch, using, "ALWAYS", the firmware number.

I think that´s the best solution and rock solid for the future ...

**Comment by JTrotta** [comment]
Done, have  a check.
I do not like this commit, it's just to check if it works. In case it will work, will create a new Board class with all information, just once.

**Comment by JTrotta** [comment]
This should work now.
Let me know, if I can. Close it.

**Pull request closed without merging**
